// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddTask'](arg1, arg2, arg3, arg4, arg5);
}

export function CheckTutorial() {
  return window['go']['main']['App']['CheckTutorial']();
}

export function CreateSchedule(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateSchedule'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function FinishTutorial() {
  return window['go']['main']['App']['FinishTutorial']();
}

export function GetReminderSettings() {
  return window['go']['main']['App']['GetReminderSettings']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetReminderSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetReminderSettings'](arg1, arg2, arg3);
}

export function ToggleTask(arg1) {
  return window['go']['main']['App']['ToggleTask'](arg1);
}

export function UpdateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3, arg4);
}
