// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddTask(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CheckTutorial():Promise<boolean>;

export function DeleteTask(arg1:number):Promise<void>;

export function FinishTutorial():Promise<void>;

export function GetTasks():Promise<Array<backend.Task>>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function ToggleTask(arg1:number):Promise<void>;
